# MINIMAL STYLE
title: Ayush Roy-Homepage
logo: /assets/img/dp.jpeg
description: PhD Student @ SUNY BUFFALO @ CVML group @ Department of Computer Science and Engineering
# show_downloads: true
theme: jekyll-theme-minimal
