title: Ayush Roy-Homepage
logo: /assets/img/dp.jpeg
description: "PhD Student @ SUNY BUFFALO @ CVML group @ Department of Computer Science and Engineering"

remote_theme: jekyll/minima

minima:
  skin: auto
  banner:
    image: /assets/img/dp.jpg

plugins:
  - jekyll-remote-theme
